  services:
    inventory-service:
      image: mysql:8.3.0
      container_name: inventory-mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3307:3306"  
      volumes:
      - ./mysql-inventory-service:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql